language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: akarni
  password:
    secure: SXPm6ynw4EZp4zPliafOO9HW3edcbnDizf4UZeVoyEfXMMGW5YWwCs4vqrccCZGShXKtYCo3BSNOu31Bsw+GfLW8H9YzGIFUEzIflIn5BsODEierG4JLQpmMeWZHe2PSyQCnyA6UuuNdXpxWu1HAMn5wA2XszkLUDdniFDzJfDufh2XjUqcsNNOtijbhLIGT2ZOtDFjNuRr/MOoMqCi5UwnMhLSDk9BsUUcYuxL9/oGyXuzTWRB8KgWfxp5xy3DmBJkzflyUnoz+OVUFfRsfqF2Q9259K9A9ofqqBiCXbFhoTEOJ3uIkefWmIP5BHnZ19RsL7Y9Y8V8BHHg5jp5kPli84ESf8s4XAjeXCIHYCzSF+3mdQbvGpCoGKtQELqHSG1dMhok8igBVbdKLPtTDFOgRlIdVoMn8RVtWR4flxImo7MqM5zPZ4Wo2kmZyCZzvhdA/CbIUqGAlhN3UihaktiIB4a2VaXrNGcuEoGg/eAF5v0S/7lcngZ5ao/dSFYe4VQmhCul7BLC7+pMXYckcKrnsYmu/oeLxqkf9+N73Yjb0+ip6rhxHpyMYdN+vgoi0M8BcE/CLNA3qEm7pQeZ9qBcm2BNwBDa0G2nl33zMNnPfv/JvS0/40MwQ6kmh4RU5vfPfW8KFhm3C8RgwbtMKIQDM6DmhBPlSvOyWLJyVo1E=
  on:
    tags: true
    repo: anilkulkarni87/simple_calculator
    python: 3.8
